[package]
name = "ime-tsf"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[lib]
name = "input_ime_tsf"
crate-type = ["cdylib", "rlib"]

[dependencies]
ime-data = { workspace = true }
ime-core = { workspace = true }
windows = { workspace = true }
windows-core = { workspace = true }
windows-registry = { workspace = true }

[build-dependencies]
winres = "0.1"
