[package]
name = "iuv-data"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
windows-core = "0.62"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[[bin]]
name = "dictc"
path = "src/bin/dictc.rs"
